spring.application.name=ProfilesApiApplication

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-weathered-cherry-ang6sruq-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_EdM7iYfQF5Ix}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.servlet.load-on-startup=1