spring.application.name=ProfilesApiApplication

# Temporary HARDCODED URL to bypass variable issues
spring.datasource.url=jdbc:postgresql://ep-summer-salad-aneiqb0b.us-east-1.aws.neon.tech/neondb?sslmode=require&stringtype=unspecified
spring.datasource.username=neondb_owner
spring.datasource.password=npg_stoAvHXUu01L
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true