spring.application.name=ProfilesApiApplication

spring.datasource.url=jdbc:postgresql://ep-weathered-cherry-ang6sruq-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_EdM7iYfQF5Ix

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.config.import=optional:file:./config/secrets.properties